# Generated by Django 5.0.6 on 2024-07-17 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='UsuarioPersonalizado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(max_length=150, unique=True)),
                ('telefono', models.CharField(default='', max_length=10, unique=True)),
                ('genero', models.CharField(choices=[('Masculino', 'Masculino'), ('Femenino', 'Femenino'), ('Otro', 'Otro')], default='Masculino', max_length=10)),
                ('direccion', models.CharField(default='', max_length=100)),
                ('estado', models.CharField(default='', max_length=100)),
                ('ciudad', models.CharField(default='', max_length=100)),
                ('puntos', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(related_name='custom_user_set_groups', related_query_name='user', to='auth.group', verbose_name='Grupo a la que pertenece')),
                ('user_permissions', models.ManyToManyField(blank=True, related_name='custom_user_set_permissions', related_query_name='user', to='auth.permission', verbose_name='Permiso del usuario')),
            ],
            options={
                'verbose_name': 'Cuenta de cliente',
                'verbose_name_plural': 'Cuentas de clientes',
            },
        ),
    ]
