# Generated by Django 5.0.6 on 2024-07-17 05:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tarjeta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tarjeta', models.CharField(max_length=16, null=True)),
                ('cvc', models.CharField(max_length=3, null=True)),
                ('fecha', models.DateField(null=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tarjetas', to='clientes.usuariopersonalizado')),
            ],
        ),
    ]
